# Generated by Django 4.1.4 on 2023-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='wallet',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
    ]
