# Generated by Django 4.1.4 on 2023-02-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusermodel_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='wallet',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
