# Generated by Django 4.1.4 on 2023-04-26 19:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customusermodel_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None),
        ),
    ]
