# Generated by Django 4.1.4 on 2023-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='payment',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
