# Generated by Django 4.1.4 on 2023-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_options_message_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
