# Generated by Django 4.1.4 on 2023-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_duration_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True),
        ),
    ]
