# Generated by Django 4.1.4 on 2023-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20),
        ),
    ]
