# Generated by Django 4.1.4 on 2023-04-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
