# Generated by Django 4.1.4 on 2023-04-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_duration_alter_message_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='duration',
        ),
    ]
