# Generated by Django 4.1.4 on 2023-04-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_message_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=7, null=True),
        ),
    ]
