# Generated by Django 4.1.4 on 2023-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_message_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
