# Generated by Django 4.1.4 on 2023-05-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_message_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='online',
        ),
    ]
